language: python
sudo: false

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.1
        - pyenv rehash
        - pyenv local 3.7.1
        - python --version
        - pip install -r requirements_dev.txt
    - os: linux
      python: 2.7
      before_install:
        - pip install -r requirements_dev27.txt
    - os: linux
      python: 3.5
      before_install:
        - pip install -r requirements_dev.txt
    - os: linux
      python: 3.7
      before_install:
        - pip install -r requirements_dev.txt

script:
  - "PYTHONPATH=. python -m pytest -v -s --cov=shconfparser tests"

after_success:
  - coveralls

