language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements_dev.txt

script:
  - "PYTHONPATH=. pytest -v -s --cov=shconfparser tests"

after_success:
  - coveralls

